# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sessionProperties.ui'
#
# Created: Mon Oct 20 11:16:52 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.editName = QtGui.QLineEdit(self.centralwidget)
        self.editName.setObjectName(_fromUtf8("editName"))
        self.gridLayout_3.addWidget(self.editName, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.timeStart = QtGui.QTimeEdit(self.centralwidget)
        self.timeStart.setObjectName(_fromUtf8("timeStart"))
        self.gridLayout_3.addWidget(self.timeStart, 1, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkDay1 = QtGui.QCheckBox(self.groupBox)
        self.chkDay1.setObjectName(_fromUtf8("chkDay1"))
        self.gridLayout.addWidget(self.chkDay1, 1, 0, 1, 1)
        self.comboRepeat = QtGui.QComboBox(self.groupBox)
        self.comboRepeat.setObjectName(_fromUtf8("comboRepeat"))
        self.comboRepeat.addItem(_fromUtf8(""))
        self.comboRepeat.addItem(_fromUtf8(""))
        self.comboRepeat.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboRepeat, 0, 0, 1, 2)
        self.chkDay4 = QtGui.QCheckBox(self.groupBox)
        self.chkDay4.setObjectName(_fromUtf8("chkDay4"))
        self.gridLayout.addWidget(self.chkDay4, 1, 3, 1, 1)
        self.chkDay5 = QtGui.QCheckBox(self.groupBox)
        self.chkDay5.setObjectName(_fromUtf8("chkDay5"))
        self.gridLayout.addWidget(self.chkDay5, 1, 4, 1, 1)
        self.chkDay2 = QtGui.QCheckBox(self.groupBox)
        self.chkDay2.setObjectName(_fromUtf8("chkDay2"))
        self.gridLayout.addWidget(self.chkDay2, 1, 1, 1, 1)
        self.chkDay6 = QtGui.QCheckBox(self.groupBox)
        self.chkDay6.setObjectName(_fromUtf8("chkDay6"))
        self.gridLayout.addWidget(self.chkDay6, 1, 5, 1, 1)
        self.chkDay3 = QtGui.QCheckBox(self.groupBox)
        self.chkDay3.setObjectName(_fromUtf8("chkDay3"))
        self.gridLayout.addWidget(self.chkDay3, 1, 2, 1, 1)
        self.chkDay7 = QtGui.QCheckBox(self.groupBox)
        self.chkDay7.setObjectName(_fromUtf8("chkDay7"))
        self.gridLayout.addWidget(self.chkDay7, 1, 6, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnAdd = QtGui.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.btnAdd.setIcon(icon)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.gridLayout_2.addWidget(self.btnAdd, 0, 0, 1, 1)
        self.btnRemove = QtGui.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.btnRemove.setIcon(icon)
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.gridLayout_2.addWidget(self.btnRemove, 0, 1, 1, 1)
        self.btnProperties = QtGui.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.btnProperties.setIcon(icon)
        self.btnProperties.setObjectName(_fromUtf8("btnProperties"))
        self.gridLayout_2.addWidget(self.btnProperties, 0, 2, 1, 1)
        self.btnPlay = QtGui.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.btnPlay.setIcon(icon)
        self.btnPlay.setObjectName(_fromUtf8("btnPlay"))
        self.gridLayout_2.addWidget(self.btnPlay, 0, 3, 1, 1)
        self.btnPause = QtGui.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-pause"))
        self.btnPause.setIcon(icon)
        self.btnPause.setObjectName(_fromUtf8("btnPause"))
        self.gridLayout_2.addWidget(self.btnPause, 0, 4, 1, 1)
        self.btnStop = QtGui.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-stop"))
        self.btnStop.setIcon(icon)
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.gridLayout_2.addWidget(self.btnStop, 0, 5, 1, 1)
        self.listMelodies = QtGui.QListWidget(self.groupBox_2)
        self.listMelodies.setObjectName(_fromUtf8("listMelodies"))
        self.gridLayout_2.addWidget(self.listMelodies, 1, 0, 1, 6)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionDiscard = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-revert"))
        self.actionDiscard.setIcon(icon)
        self.actionDiscard.setObjectName(_fromUtf8("actionDiscard"))
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionDiscard)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Nombre", None))
        self.label_2.setText(_translate("MainWindow", "Hora", None))
        self.groupBox.setTitle(_translate("MainWindow", "Repetir", None))
        self.chkDay1.setText(_translate("MainWindow", "Lunes", None))
        self.comboRepeat.setItemText(0, _translate("MainWindow", "De lunes a viernes", None))
        self.comboRepeat.setItemText(1, _translate("MainWindow", "Todos los días", None))
        self.comboRepeat.setItemText(2, _translate("MainWindow", "Días sueltos", None))
        self.chkDay4.setText(_translate("MainWindow", "Jueves", None))
        self.chkDay5.setText(_translate("MainWindow", "Viernes", None))
        self.chkDay2.setText(_translate("MainWindow", "Martes", None))
        self.chkDay6.setText(_translate("MainWindow", "Sábado", None))
        self.chkDay3.setText(_translate("MainWindow", "Miércoles", None))
        self.chkDay7.setText(_translate("MainWindow", "Domingo", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Melodías", None))
        self.btnAdd.setText(_translate("MainWindow", "...", None))
        self.btnRemove.setText(_translate("MainWindow", "...", None))
        self.btnProperties.setText(_translate("MainWindow", "...", None))
        self.btnPlay.setText(_translate("MainWindow", "...", None))
        self.btnPause.setText(_translate("MainWindow", "...", None))
        self.btnStop.setText(_translate("MainWindow", "...", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionSave.setText(_translate("MainWindow", "Guardar cambios", None))
        self.actionSave.setToolTip(_translate("MainWindow", "<html><head/><body><p>Guarda los cambios realizados.</p></body></html>", None))
        self.actionDiscard.setText(_translate("MainWindow", "Descartar cambios", None))
        self.actionDiscard.setToolTip(_translate("MainWindow", "<html><head/><body><p>Descarta los cambios realizados.</p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

